export const ROUTES = {
  ROOT: '/',
  STATUS_CHECK: '/status-check',
  DOWNLOAD: '/download',
  AUTH: '/auth',
  PROMPT: '/prompt',
  RESPONSE: '/response',
  INFO: '/info',
  REPORTS_LATEST: '/reports/latest',
  REPORT_DETAIL: (name: string) => `/reports/${name}`,
  GUIDE_INVESTMENT: '/guide/investment',
  GUIDE_VALUATION: '/guide/valuation',
  GUIDE_TECHNICAL_ANALYSIS: '/guide/technical-analysis',
  GUIDE_TECHNICAL_ANALYSIS_CATEGORY: (categoryId: string) => `/guide/technical-analysis/${categoryId}`,
} as const
